name = "v2ray-config-bot"
compatibility_date = "2023-08-01"
account_id = "dcb5cb4caca718bf2af93c10267ac007"
workers_dev = true

[vars]
TELEGRAM_BOT_TOKEN = "7626291818:AAG7dEWhfWZBu8j9i7JWQ71vzNpz9h7UZq0"
