name = "v2ray-config-bot"
compatibility_date = "2023-08-01"
account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"
workers_dev = true

[vars]
TELEGRAM_BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"

[[rules]]
type = "json"
globs = ["**/*.json"]
fallthrough = true
