name = "v2ray-config-bot"
compatibility_date = "2023-08-01"
account_id = "03a4700138e72b9c57362b0423c93d98"  # Replace with your Cloudflare account ID
workers_dev = true
main = "src/worker.js"

[vars]
TELEGRAM_BOT_TOKEN = "8089020053:AAGLM8BIRlEx64Zsi4IQ6SMbq-XosbfFLv8"  # Will be overridden by GitHub Secrets
